### ISSUE TITLE
After initial start of image, GUI doesn't start

### ISSUE THREAD

**Issue by apeltzer** [apeltzer/deager#4]
NFO: 2015/12/06 19:39:24 TLS is disabled
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
/usr/local/src/github.con/apeltzer/deager/deager.go:127 +0x21b8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

**Comment by ChristianKniep** [comment]
Kannst du das command und `env` hinzufügen?

**Comment by ChristianKniep** [comment]
Linux oder Mac?

**Comment by apeltzer** [comment]
Linux Maschine:
Command: ./deager gui --gatk /home/seitz/tests/EAGER/gatk

XDG_VTNR=2
XDG_SESSION_ID=c3
TERMINATOR_UUID=urn:uuid:ea818d81-5455-415a-b215-9abdf4870192
IBUS_DISABLE_SNOOPER=1
PICARD_HOME=/usr/share/java/picard-tools
QT_STYLE_OVERRIDE=gtk
TERM=xterm
SHELL=/bin/bash
DOCKER_HOST=unix:///var/run/docker.sock
WINDOWID=111149060
OLDPWD=/home/seitz/tests/EAGER/deager
GTK_MODULES=canberra-gtk-module
SWT_GTK3=0
ANT_HOME=/usr/share/apache-ant
USER=seitza
CLUTTER_BACKEND=x11
DESKTOP_AUTOSTART_ID=105f82872ef63bc9ce144897921796843600000088700001
SESSION_MANAGER=local/epimetheus:@/tmp/.ICE-unix/8870,unix/epimetheus:/tmp/.ICE-unix/8870
USERNAME=seitza
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
PATH=/homes/seitza/scripts:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/seitz/edirect
MAIL=/var/spool/mail/seitza
DESKTOP_SESSION=cinnamon
HG=/usr/bin/hg
XDG_SESSION_TYPE=x11
PWD=/home/seitz/tests/EAGER/deager/amd64
LANG=C
GDM_LANG=C
GDMSESSION=cinnamon
SSH_ASKPASS=/usr/lib/seahorse/seahorse-ssh-askpass
XDG_SEAT=seat0
HOME=/home/seitz
SHLVL=1
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
XDG_SESSION_DESKTOP=cinnamon
LOGNAME=seitza
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/13559/bus
GOPATH=/home/seitz/go
WINDOWPATH=2
XDG_RUNTIME_DIR=/run/user/13559
DISPLAY=:1
XDG_CURRENT_DESKTOP=X-Cinnamon
BCFTOOLS_PLUGINS=/usr/lib/bcftools
COLORTERM=gnome-terminal
XAUTHORITY=/run/user/13559/gdm/Xauthority
_=/usr/bin/env

**Comment by ChristianKniep** [comment]
Erst einmal sollte gui am ende stehen und zweitens setzte bitte `--data`

**Comment by apeltzer** [comment]
Leider gleiche Fehlermeldung, auch wenn die options vorne stehen:

./deager --gatk /home/seitz/tests/EAGER/gatk --data /home/seitz/tests/EAGER/data gui

**Comment by ChristianKniep** [comment]
Hmm... Das ist ja gar nicht dein home-directory!1!! :)
Muss ich mir mal anschauen, gui hatte ich auf Linux nicht getestet, da ich keine Linux-Büchse habe.
Vlt. kann ich dies woanders testen...

**Comment by ChristianKniep** [comment]
Sorry, dude - I am looking into it...

**Comment by ChristianKniep** [comment]
Fixed by https://github.com/apeltzer/deager/commit/aecc2625d08e73e482b0cd3158d639a78da037b6
