### ISSUE TITLE
Container command not found or does not exist

### ISSUE THREAD

**Issue by apeltzer** [apeltzer/deager#5]
Hi,

Operating system: Ubuntu 15.04 / Windows 10 64 bit (apparently same behaviour on both systems9.

Using docker compose, we try to set up the eager container:

`~/Downloads/deager$ docker-compose up

Removing deager_build

Starting 5182f7036ef7_5182f7036ef7_deager_build

ERROR: for daeger  Container command not found or does not exist.
`

Nothing happens...

**Comment by apeltzer** [comment]
Can't say whats going on, this seems to be a Docker problem unfortunately: 

https://github.com/docker/docker/pull/21345

**Comment by ChristianKniep** [comment]
I am afraid that was my bad as the path has a slight typo `/usr/local/src/github.con/apeltzer/deager/amd64/build.sh`. :(

```
diff --git a/docker-compose.yml b/docker-compose.yml
index ba877eb..8a4ff6a 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,6 +1,6 @@
 daeger:
     volumes:
-     - ./:/usr/local/src/github.con/apeltzer/deager/
+     - ./:/usr/local/src/github.com/apeltzer/deager/
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/:/data/
      - ~/gatk/:/gatk/
```

I created a PR #6

**Comment by apeltzer** [comment]
This seems to be done
