### ISSUE TITLE
SSH key Checking

### ISSUE THREAD

**Issue by apeltzer** [apeltzer/deager#8]
If we already have started a container before, stop/remove it and then start the container later on again, the ~/.ssh/known_hosts file contains entries for the SSH connection to the old container, thus not allowing us to start a GUI connection to the new container. 

Maybe we should remove the entry from the host once we issue ./deager stop. 
<img width="1005" alt="screen shot 2016-04-26 at 12 31 23" src="https://cloud.githubusercontent.com/assets/2359510/14815291/cebde388-0baa-11e6-93ea-e386ace97aa0.png">

**Comment by apeltzer** [comment]
Can we maybe reset the local "known_hosts" entry on ./deager start everytime or force the SSH command to not check the image ?

This way the error messages when updating the image are gone... had this now for quite some times...

**Comment by apeltzer** [comment]
Okay, this is currently still a problematic issue as everytime when users try to spin up the container the container gets a new SSH fingerprint, thus producing a cryptic error message once somebody starts gui/executes configs with the docker image. 

We need to figure out a way to remove the current line for the IP / hostname on the host machine using deager once we start a container the first time, so this is not happening anymore.

**Comment by ChristianKniep** [comment]
There is a way of suppressing the known-host usage to begin with.

**Comment by apeltzer** [comment]
Which I added now - this fixes the possible problems in 2c58809771ed881759a993a5ada30b8dc5724e90
