### ISSUE TITLE
Issues when specifying --uid on container start

### ISSUE THREAD

**Issue by apeltzer** [apeltzer/deager#9]
For some environment,the correct usage of the same UID/GID inside the container is required to keep access permissions up and running. 

./deager start --data /path/to/data --uid #t 

starts the container successfully, however when executing the GUI, the connection asks for a password:

./deager gui

**Comment by apeltzer** [comment]
Do you have a clue what might have gone wrong here ?

**Comment by ChristianKniep** [comment]
I suppose that if you change the UID you won't use the private-sshkey of the predefined user.
Thus it will ask for the password.

I rather would use the user-namespace to not care about, which user is used within the container, but map any user inside the container to a known user outside of it.

**Comment by apeltzer** [comment]
This sounds indeed great and probably the most failure-proof solution. I guess this is solely something we should be setting up in the ./deager start command... I will look at this asap.

**Comment by apeltzer** [comment]
This was an issue with creating user and group ids in the image. Fixed by changing the commands to generate group first with proper GID and then creating user with that group - works now flawlessly 👍
